[features]
seeds = false
[programs.localnet]
mint_nft = "HQ4rP2qrmq6D2mBCd9ZLaUe3NaGVQAG2zq6tMxtBhsmD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ali/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
